[project]
name = "jamboree"
version = "0.1.0"
dependencies = ["flask", "pyserial", "paramiko", "requests"]
requires-python = ">=3.11"

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"
